[package]
name = "common-functions"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../arrow" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../exception" }
common-io = { path = "../io" }

# Github dependencies
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "c33837e" }

# Crates.io dependencies
dyn-clone = "1.0.4"
once_cell = "1.9.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
bytes = "1.1.0"
num = "0.4.0"
ordered-float = "2.10.0"
crc32fast = "1.3.1"
sha1 = "0.10.0"
sha2 = "0.10.1"
md5 = "0.7.0"
blake3 = "1.3.1"
twox-hash = "1.6.2"
rand = "0.8.4"
hex = "0.4.3"
regex = "1.5.4"
paste = "1.0.6"
bumpalo = "3.9.1"
simdutf8 = "0.1.3"
base64 = "0.13.0"
itertools = "0.10.3"
num-format = "0.4.0"
bstr = "0.2.17"
uuid = { version = "0.8.2", features = ["v4"] }
strength_reduce = "0.2.3"
num-traits = "0.2.14"
naive-cityhash = "0.2.0"

[dev-dependencies]
bumpalo = "3.9.1"
common-datablocks = { path = "../datablocks" }
pretty_assertions = "1.1.0"
float-cmp = "0.9.0"
