[package]
name = "common-base"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[features]
tracing = ["tokio/tracing"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-tracing = { path = "../tracing" }
common-exception = { path = "../exception" }

# Github dependencies

# Crates.io dependencies
async-trait = "0.1.52"
ctrlc = { version = "3.2.1", features = ["termination"] }
futures = "0.3.21"
pprof = { version = "0.6.2", features = ["flamegraph", "protobuf"] }
tokio = { version = "1.16.1", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
serde = { version = "1.0.136", features = ["derive"] }
poem = { version = "1.2.53", features = ["rustls"] }
