[package]
name = "common-meta-types"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../exception" }

anyerror = "0.1.3"
derive_more = "0.99.17"
enumflags2 = { version = "0.7.3", features = ["serde"] }
lazy_static = "1.4.0"
maplit = "1.0.2"
openraft = { git = "https://github.com/datafuselabs/openraft", rev = "f633756d60152d171909aea56f80d18905cd4002"}
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1",default-features = false }
once_cell = "1.9.0"
prost = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
thiserror = "1.0.30"
tonic = { version = "0.6.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
sha1 = "0.10.0"
sha2 = "0.10.1"
hex = "0.4.3"

[build-dependencies]
common-building = { path = "../../building" }
tonic-build = "0.6.2"

[dev-dependencies]
anyhow = "1.0.53"
