name: "Test meta data compatibility with openraft-07"
description: ""
inputs:
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        artifacts: metactl,meta

    - name: Test meta-data-compat-openraft-07
      shell: bash
      run: |
        bash ./tests/meta-data-compat-openraft-07/test-meta-data-compat-openraft-08.sh
        bash ./tests/meta-data-compat-openraft-07/test-sm-compat-v0-v002.sh
