[package]
name = "common-management"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base= {path = "../base" }
common-datavalues = {path = "../datavalues" }
common-exception= {path = "../exception"}
common-meta-api= {path = "../meta/api" }
common-meta-types= {path = "../meta/types"}
common-tracing= {path = "../tracing"}
common-functions= {path = "../functions"}
common-ast= {path = "../ast"}

async-trait = "0.1.52"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
tempfile = "3.3.0"


[dev-dependencies]
common-base = { path = "../base" }
common-meta-embedded = {path = "../meta/embedded" }

mockall = "0.11.0"
tempfile = "3.3.0"
