[package]
name = "common-dal-context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-infallible = { path = "../infallible" }

opendal = "0.0.3"
async-trait = "0.1.52"