[package]
name = "storage-encryption"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../../common/base" }
common-exception = { path = "../../../common/exception" }

# Github dependencies
async-trait = "0.1.57"

[build-dependencies]
