[package]
name = "common-datavalues"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../arrow" }
common-exception = { path = "../exception" }
common-io = { path = "../io" }
common-macros = { path = "../macros" }
common-mem-allocator = { path = "../mem-allocator" }
common-clickhouse-srv = { path = "../clickhouse-srv" }

# Github dependencies

# Crates.io dependencies
num = "0.4.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.78"

lexical-core = "0.8.2"
chrono = "0.4.19"
chrono-tz = "0.6.1"
ordered-float = "2.10.0"
paste = "1.0.6"
dyn-clone = "1.0.4"
typetag = "0.1.8"
itertools = "0.10.3"
once_cell = "1.9.0"


[dev-dependencies]
pretty_assertions = "1.1.0"
