[package]
name = "common-meta-sled-store"
version = "0.1.0"
description = "Sled store backend for raft state machine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../exception" }
common-tracing = { path = "../../tracing" }
common-meta-types = { path = "../types" }

anyhow = "1.0.53"
byteorder = "1.4.3"
once_cell = "1.9.0"
serde = { version = "1.0.136", features = ["derive"] }
openraft = { git = "https://github.com/datafuselabs/openraft", rev = "f633756d60152d171909aea56f80d18905cd4002"}
serde_json = "1.0.78"
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }
tempfile = "3.3.0"


[dev-dependencies]
common-base = { path = "../../base" }
