[package]
name = "common-io"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-exception= {path = "../exception"}
bytes = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }

# Github dependencies
bincode = { git = "https://github.com/datafuse-extras/bincode", rev = "fd3f9ff" }

[dev-dependencies]
rand = "0.8.4"
