[package]
name = "common-containers"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-base = {path = "../base"}
common-tracing = {path = "../tracing"}

async-trait = "0.1.52"

[dev-dependencies]
anyhow = "1.0.53"
