[package]
name = "common-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
quote = "1.0.15"
proc-macro2 = "1.0.36"
syn = { version = "1.0.86", features = ["full"] }
synstructure = "0.12.6"
