# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# Databend Query http address.
# For admin RESET API.
http_api_address = "0.0.0.0:8081"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7071"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

# Databend Query ClickHouse Handler.
clickhouse_handler_host = "0.0.0.0"
clickhouse_handler_port = 9001

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8001

# In mgr mode, we also need to config the tenant_id, such as system.
tenant_id = "system"
cluster_id = "system_mgr_1"
# Management mode enable.
management_mode = true


[log]
log_level = "INFO"
log_dir = "./_logs"

[meta]
# To enable embedded meta-store, set meta_address to ""
meta_address = "0.0.0.0:9191"
meta_username = "root"
meta_password = "root"
meta_client_timeout_in_second = 60

# Storage config.
[storage]
# disk|s3
storage_type = "disk"

# DISK storage.
[storage.disk]
data_path = "management_data"

# S3 storage.
[storage.s3]

# Azure storage
[storage.azure_storage_blob]