name: Slack Notify Result
on:
  workflow_run:
    workflows: [ run_perf, rerun_perf ]
    types:
      - completed
jobs:
  slack-notification-result:
    name: Slack Notification Result
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification Failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/80994548?s=200&v=4
          SLACK_COLOR: black
          SLACK_CHANNEL: databend
          SLACK_MESSAGE: 'databend performance test failed!'
          SLACK_TITLE: performance test failed
          SLACK_USERNAME: databend messager
      - name: Slack Notification Start
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/80994548?s=200&v=4
          SLACK_COLOR: green
          SLACK_CHANNEL: databend
          SLACK_MESSAGE: 'databend performance test success!'
          SLACK_TITLE: performance test success
          SLACK_USERNAME: databend messager
